version: '3.6'

networks:
  monitoring-network:
    driver: overlay
    attachable: true

services:

  alertmonitor:
    image: matjaz99/alertmonitor:latest
    ports:
      - 8080:8080
    networks:
      - monitoring-network
    environment:
      - SIMPLELOGGER_FILENAME: /opt/alertmonitor/log/akertmonitor.log
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
