version: '3.6'

networks:
  monitoring_network:
    driver: overlay
    attachable: true

volumes:
  mongodb_storage:
    driver: local

services:

  alertmonitor:
    image: matjaz99/alertmonitor:latest
    ports:
      - 8080:8080
    networks:
      - monitoring_network
    environment:
      - TZ=${TZ}
      - SIMPLELOGGER_FILENAME=/opt/jboss/alertmonitor/log/alertmonitor.log
      - GRAFANA_HOSTNAME=my.grafana.domain
      - ALERTMONITOR_DATA_RETENTION_DAYS=7
      - ALERTMONITOR_PSYNC_INTERVAL_SEC=900
      - ALERTMONITOR_PROMETHEUS_SERVER=http://localhost:9090
      - ALERTMONITOR_PROMETHEUS_CLIENT_POOL_SIZE=1
      - ALERTMONITOR_HTTP_CLIENT_CONNECT_TIMEOUT_SEC=10
      - ALERTMONITOR_HTTP_CLIENT_READ_TIMEOUT_SEC=120
      - ALERTMONITOR_DATE_FORMAT="yyyy/MM/dd H:mm:ss"
      - ALERTMONITOR_KAFKA_ENABLED=false
      - ALERTMONITOR_KAFKA_SERVER=promvm:9092
      - ALERTMONITOR_KAFKA_TOPIC=alertmonitor_events
      - ALERTMONITOR_PROMETHEUS_ID_LABELS="cluster, region, monitor"
      - ALERTMONITOR_MONGODB_ENABLED=false
      - ALERTMONITOR_MONGODB_CONNECTION_STRING="mongodb://admin:mongodbpassword@mongodb:27017/?authSource=admin"
      - ALERTMONITOR_MONGODB_CONNECT_TIMEOUT_SEC="5"
      - ALERTMONITOR_MONGODB_READ_TIMEOUT_SEC="30"
    volumes:
      # set permissions: chown 1000:1000 /var/log/alertmonitor
      - /var/log/alertmonitor:/opt/jboss/alertmonitor/log
      - ./providers.yml:/opt/jboss/alertmonitor/providers.yml
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    networks:
      - monitoring_network
    environment:
      MONGO_INITDB_DATABASE: "alertmonitor"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "mongodbpassword"
    volumes:
      - mongodb_storage:/data/db
    deploy:
      mode: replicated
      replicas: 1

