version: '3.6'

networks:
  monitoring-network:
    driver: overlay
    attachable: true

services:

  alertmonitor:
    image: matjaz99/alertmonitor:latest
    ports:
      - 8080:8080
    networks:
      - monitoring-network
    environment:
      - SIMPLELOGGER_FILENAME: /opt/alertmonitor/log/alertmonitor.log
      - SIMPLELOGGER_LEVEL: INFO
      - SIMPLELOGGER_APPEND: true
      - SIMPLELOGGER_VERBOSE: true
      - SIMPLELOGGER_MAXFILESIZE: 10
      - SIMPLELOGGER_MAXBACKUPFILES: 3
      - SIMPLELOGGER_DATEFORMAT: "yyyy.MM.dd hh:mm:ss:SSS"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
