version: '3.6'

networks:
  monitoring_network:
    driver: overlay
    attachable: true

services:

  alertmonitor:
    image: matjaz99/alertmonitor:latest
    ports:
      - 8080:8080
    networks:
      - monitoring_network
    environment:
      - SIMPLELOGGER_FILENAME=/opt/alertmonitor/log/alertmonitor.log
      - GRAFANA_HOSTNAME=my.grafana.domain
      - ALERTMONITOR_DATA_RETENTION_DAYS=7
      - ALERTMONITOR_PSYNC_INTERVAL_SEC=900
      - ALERTMONITOR_PROMETHEUS_SERVER=http://localhost:9090
      - ALERTMONITOR_DATE_FORMAT="yyyy/MM/dd H:mm:ss"
      - ALERTMONITOR_KAFKA_ENABLED=false
      - ALERTMONITOR_KAFKA_SERVER=promvm:9092
      - ALERTMONITOR_KAFKA_TOPIC=alertmonitor_events
      - ALERTMONITOR_PROMETHEUS_ID_LABELS="cluster, region, monitor"
      - ALERTMONITOR_MONGODB_ENABLED=false
      - ALERTMONITOR_MONGODB_CONNECTION_STRING="mongodb://admin:mongodbpassword@promvm:27017/test?w=majority&authSource=admin"
    volumes:
      - /var/log:/opt/alertmonitor/log
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
