version: '3.6'

networks:
  monitoring-network:
    driver: overlay
    attachable: true

services:

  alertmonitor:
    image: matjaz99/alertmonitor:latest
    ports:
      - 8080:8080
    networks:
      - monitoring-network
    deploy:
      mode: replicated
      replicas: 1
