global:
  name: am-1
  journal:
    size: 20000
  date:
    format: 'yyyy/MM/dd H:mm:ss'
providers:
  - source: prometheus
    name: prom1
    server: http://prom-1:9090
    sync:
      interval: 60s
  - source: prometheus
    name: prom2
    server: http://prom-2:9090
    sync:
      interval: 120s
  - source: eventlogger
    name: cluster-1
    server: http://hostname:8080/eventlogger/api/v1/alarms
    sync:
      interval: 60s
kafka:
  - host: kafka:9092
    topic: topic_name
    enabled: false

