{
 "title": "Alertmonitor stats",
 "tags": [
  "Prometheus",
  "Alerts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(alertmonitor_build_info{app=\"Alertmonitor\"} , instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_build_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_build_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Time since last event",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_last_event_timestamp{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Webhook messages total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_webhook_messages_received_total{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Journal events total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_journal_messages_total{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Alerts balance factor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "alertmonitor_alerts_balance_factor{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Messages received on webhook",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_webhook_messages_received_total{instance=\"$node\"}[5m])) by (method) / 4 * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active alerts by severity (stacked)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Journal events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_journal_messages_total{instance=\"$node\"}[5m])) by (severity) * 60 / 4",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts by alertname",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Alerting events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_active_alerts_count{instance=\"$node\", severity=~\"critical|major|minor|warning\"}[5m])) by (severity) * 15",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts by severity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}