{
 "title": "Alertmonitor 2.0 stats",
 "tags": [
  "Prometheus",
  "Alerts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(alertmonitor_build_info{app=\"Alertmonitor\"} , instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_build_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_build_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Time since last event",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_last_event_timestamp{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Webhook messages total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_webhook_messages_received_total{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Journal events total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_journal_messages_total{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "PSync interval",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmonitor_psync_interval_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Messages received on webhook",
   "type": "timeseries",
   "description": "Number of HTTP messages received on webhook",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_webhook_messages_received_total{instance=\"$node\"}[5m])) by (method) / 4 * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active alerts by severity (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Alerts balance factor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "alertmonitor_alerts_balance_factor{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Journal events",
   "type": "timeseries",
   "description": "Number of events entering into journal",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_journal_messages_total{instance=\"$node\"}[5m])) by (severity) * 60 / 4",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts by alertname",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Active alerts pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Firing alerts",
   "type": "timeseries",
   "description": "Number of new alerts added to active alert list",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_active_alerts_count{instance=\"$node\"}[5m])) by (severity) * 15",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts by severity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count{instance=\"$node\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(alertmonitor_prom_api_duration_seconds_sum{instance=\"$node\"}[5m])) by (endpoint, method) / sum(rate(alertmonitor_prom_api_duration_seconds_count{instance=\"$node\"}[5m])) by (endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Percentage of requests with response time less than 100ms",
   "type": "timeseries",
   "description": "You might have an SLA to serve 95% of requests within 100ms. In that case, configure a histogram to have a bucket with an upper limit of 0.3 seconds. You can then directly express the relative amount of requests served within 300ms and easily alert if the value drops below 0.95.",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(alertmonitor_prom_api_duration_seconds_bucket{le=\"0.1\", instance=\"$node\"}[5m])) by (endpoint) / sum(rate(alertmonitor_prom_api_duration_seconds_count{instance=\"$node\"}[5m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request duration within which Alertmonitor has served N% of requests",
   "type": "timeseries",
   "description": "This time, you do not want to display the percentage of requests served within 300ms, but instead the 95th percentile, i.e. the request duration within which you have served 95% of requests. To do that, you can either configure a summary with a 0.95-quantile and (for example) a 5-minute decay time, or you configure a histogram with a few buckets around the 300ms mark",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(alertmonitor_prom_api_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(alertmonitor_prom_api_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(alertmonitor_prom_api_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  }
 ]
}