{
 "title": "Alertmonitor stats",
 "tags": [
  "Prometheus",
  "Alerts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    { "expr": "alertmonitor_build_info" }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "alertmonitor_build_info" }
   ]
  },
  {
   "title": "Last event timestamp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertmonitor_last_event_timestamp"
    }
   ]
  },
  {
   "title": "Time since last event",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertmonitor_last_event_timestamp"
    }
   ]
  },
  {
   "title": "Messages received on webhook",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_webhook_messages_received_total[5m])) by (method) / 4 * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active alerts by severity (stacked)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Webhook received total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_webhook_messages_received_total)"
    }
   ]
  },
  {
   "title": "Journal events total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_journal_messages_total)"
    }
   ]
  },
  {
   "title": "Journal events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_journal_messages_total[5m])) by (severity) * 60 / 4",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts by alertname",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count)"
    }
   ]
  },
  {
   "title": "Alerts balance factor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "alertmonitor_alerts_balance_factor"
    }
   ]
  },
  {
   "title": "Alerting events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_active_alerts_count{severity=~\"critical|major|minor|warning\"}[5m])) by (severity) * 60 / 4",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts by severity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active alerts pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}