{
 "title": "Alertmonitor stats",
 "tags": [
  "Prometheus",
  "Alerts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    { "expr": "alertmonitor_build_info" }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "alertmonitor_build_info" }
   ]
  },
  {
   "title": "Last event timestamp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertmonitor_last_event_timestamp"
    }
   ]
  },
  {
   "title": "Messages received on webhook",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmonitor_webhook_messages_received_total[5m])) by (method) / 4 * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Journal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmonitor_journal_messages_total",
     "legendFormat": "Journal"
    }
   ]
  },
  {
   "title": "Webhook received total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_webhook_messages_received_total)"
    }
   ]
  },
  {
   "title": "Journal received total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_journal_messages_total)"
    }
   ]
  },
  {
   "title": "Active alerts by severity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmonitor_active_alerts_count",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Raising vs. clearing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "alertmonitor_alerts_total", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Active alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(alertmonitor_active_alerts_count)"
    }
   ]
  },
  {
   "title": "Alerts balance factor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "alertmonitor_alerts_balance_factor"
    }
   ]
  }
 ]
}